# Generated by Django 4.1.7 on 2023-03-05 21:44

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("iso_code", models.CharField(max_length=3)),
                ("verbose_name", models.CharField(max_length=128)),
                ("sign", models.CharField(max_length=1)),
            ],
            options={
                "verbose_name": "Currency",
                "verbose_name_plural": "Currencies",
                "db_table": "currency",
            },
        ),
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        default="main",
                        help_text="Account name used in user interface",
                        max_length=64,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        db_index=True,
                        help_text="ID from User Service or any other User ID that we need",
                    ),
                ),
                (
                    "merchant_id",
                    models.CharField(
                        choices=[("capital_com_fca", "Capital.com FCA Licence")],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="For disable purposes"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, help_text="For delete purposes"),
                ),
                (
                    "ccy",
                    models.ForeignKey(
                        choices=[("GBP", "Great Britain Pound")],
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="wallets",
                        to="wallet_app.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet",
                "verbose_name_plural": "Wallets",
                "db_table": "wallet",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=19
                    ),
                ),
                (
                    "ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions",
                        to="wallet_app.currency",
                    ),
                ),
                (
                    "from_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_from",
                        to="wallet_app.wallet",
                    ),
                ),
                (
                    "to_wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transactions_to",
                        to="wallet_app.wallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transactions",
                "db_table": "transaction",
            },
        ),
        migrations.CreateModel(
            name="Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("rate_value", models.DecimalField(decimal_places=2, max_digits=19)),
                (
                    "from_ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rates_from",
                        to="wallet_app.currency",
                    ),
                ),
                (
                    "to_ccy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="rates_to",
                        to="wallet_app.currency",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rate",
                "verbose_name_plural": "Rates",
                "db_table": "rate",
            },
        ),
        migrations.AddConstraint(
            model_name="wallet",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_active", True)),
                fields=("user_id", "merchant_id", "user_id", "ccy"),
                name="unique_active_wallet_per_user_per_ccy",
                violation_error_message="It's not possible to add additional Wallet with this Currency to this User",
            ),
        ),
    ]
