# Generated by Django 4.1.7 on 2023-03-06 00:38

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wallet_app", "0002_alter_currency_sign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rate",
            name="rate_value",
            field=models.DecimalField(decimal_places=2, max_digits=17),
        ),
        migrations.AlterField(
            model_name="transaction",
            name="amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=17
            ),
        ),
    ]
